// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKnzW2v1N6cePVVe14NxzVxNfSCSGy_0Y',
    appId: '1:762647593278:web:a3c90d351570113c212c6f',
    messagingSenderId: '762647593278',
    projectId: 'weather-app-32f23',
    authDomain: 'weather-app-32f23.firebaseapp.com',
    storageBucket: 'weather-app-32f23.appspot.com',
    measurementId: 'G-1331H0GTBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGUalZGF2S-drOwuZegAlpLnOgu2HrUCE',
    appId: '1:762647593278:android:6aa5198e98057b51212c6f',
    messagingSenderId: '762647593278',
    projectId: 'weather-app-32f23',
    storageBucket: 'weather-app-32f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj4zwp5nqiG2wPtJ79DnHsUFUEKDboNKQ',
    appId: '1:762647593278:ios:52c636d6c12db939212c6f',
    messagingSenderId: '762647593278',
    projectId: 'weather-app-32f23',
    storageBucket: 'weather-app-32f23.appspot.com',
    iosBundleId: 'com.example.practiceProjectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj4zwp5nqiG2wPtJ79DnHsUFUEKDboNKQ',
    appId: '1:762647593278:ios:f8a55659424b4d68212c6f',
    messagingSenderId: '762647593278',
    projectId: 'weather-app-32f23',
    storageBucket: 'weather-app-32f23.appspot.com',
    iosBundleId: 'com.example.practiceProjectFlutter.RunnerTests',
  );
}
